### ISSUE TITLE
Breakout Proposal: Containers on HPC

### ISSUE THREAD

**Issue by pgierz** [DE-RSE/un-deRSE23-breakouts#11]
Moin together! 

We (@mandresm, @BFrit and myself) would like to propose a breakout session to go a little bit into detail regarding challenges and successes of containerisation on HPC. I recently taught a course together with @WilliRath and the interest among the "standard research scientist" (so, those less inclined towards engineering) certainly seems to be growing. I think it would be nice to dive a little deeper into this topic at RSE.

Happy Easter from us at AWI!
Paul  

- - - 
Abstract:

## Containerisation on HPC

Oftentimes, scientific computing is faced with the challenge of providing an easily distributable reproduction of a particular simulation, AI model, or a similarly numerically intensive task. Software containers have been a success for providing a portable solution for exactly this problem, with the [`singularity` and `apptainer`](https://apptainer.org) technologies so far proving to be best suited for HPC applications. This breakout group proposes to gather ideas, challenges, and success stories from the community.

**Comment by pancetta** [comment]
I'd be very interested in this topic, too!

**Comment by pancetta** [comment]
Hi @pgierz, interesting proposal, thanks! As we're (slowly) moving toward more specific submissions, could you please add more details to the proposal? We'd need 1-3 people responsible for the BOS, a short abstract/appetizer incl. stuff attendees can take away from that and so on. How would you run the session? Is this more a discussion or a lecture? Hands on or off?

**Comment by BFrit** [comment]
Hi @pancetta , as @pgierz is in vacation, I will jump in. The idea is to initiate a discussion forum for exchange of different experiences with containers in HPC. We are interested in success stories in order to learn about (best or at least successful) practices, but also to hear about the problems which can arise and how to address them.

**Comment by pancetta** [comment]
Sounds good to me! How would you organize this? Let people come and talk? Or identify speakers/attendees beforehand?

**Comment by pgierz** [comment]
Hi @pancetta, sorry for the late response.

I can volunteer to be "Break Out Leader" and moderate. I would suggest to advertise the session in general, but keep it fairly informal. It would be best to have one (maybe two) interesting talks from the community to stimulate some discussion, and then just use the rest of the time to discuss and trade stories. If everyone is feeling shy and no one wants to give a talk, I can talk for 10 minutes about what we are doing with containers at AWI. Do you know of any mailing list or other forums (other than here on GitHub) I could use to ask for interested speakers?

If it turns out to be the case that I start with a small talk, I'll send you a more detailed abstract than what I have above. When would you need that by?

**Comment by pancetta** [comment]
Sounds good to me! You could try the [derse-Channel](https://chat.gwdg.de/channel/derse), and we also advertise the BOS issues in our weekly publicity rampage. Also, did you have a look at #16?

We'd need final BOS submission by May 28.

**Comment by HeidiSeibold** [comment]
@timsu100 and @EricKrg (break-out #16) said that they would be interested to join forces with this session.

Would you be open to that @BFrit and @pgierz? 

If you do join forces, can you close one of the issues and describe how you'll do it? Thank you 🙏 

Also, I added a [label](https://github.com/DE-RSE/un-deRSE23-breakouts/labels) to this break-out. Can you check if you feel it is appropriate and change it if not? Let me know if you have any questions.

**Comment by HeidiSeibold** [comment]
Could you please answer the following questions for me?

### Who could be interested in collaborating on this?
(feel free to tag them with their GitHub username if they have one)

### How much time do you need for this?
(90 minutes or multiples thereof)

### Abstract
(Can be short)

**Comment by HeidiSeibold** [comment]
Hi @pgierz  can you please respond by Tuesday morning, thanks 😃

**Comment by pgierz** [comment]
Hi @HeidiSeibold,

sorry for the late reply! :-(

I have no problem merging with a different group. I would close this issue and start to contributing to the other one.
