### ISSUE TITLE
position paper on RSE groups

### ISSUE THREAD

**Issue by knarrff** [DE-RSE/un-deRSE23-breakouts#19]
At deRSE23, work was started on a position paper on the state and vision of RSE groups in the German academic system. This is on-going work (slow at the moment, but on-going) and we (@dokempf, @jlinx, and I)  would like to use this opportunity to involve the community again.

**Comment by HeidiSeibold** [comment]
Thanks @knarrff, how much time would you like to plan for this?

**Comment by HeidiSeibold** [comment]
I added a [label](https://github.com/DE-RSE/un-deRSE23-breakouts/labels) to this break-out. Can you check if you feel it is appropriate and change it if not? Let me know if you have any questions.

**Comment by dokempf** [comment]
Feels appropriate, maybe additionally adding the `Discussion` label would be a good fit (not allowed to do so myself)

**Comment by HeidiSeibold** [comment]
So what I need from you to be able to make a decision on this breakout are the following infos:


### Who could be interested in collaborating on this?
(feel free to tag them with their GitHub username if they have one)

Anybody beyond @dokempf, @jlinx, and @knarrff?

### How much time do you need for this?
90 minutes

### Abstract
(Can be short)

**Comment by HeidiSeibold** [comment]
Hi @knarrff  can you please respond by Tuesday morning, thanks 😃

**Comment by pancetta** [comment]
Hi! I just added the "Accepted" label to this BOS. Welcome on board!
https://un-derse23.sciencesconf.org/program

**Comment by pancetta** [comment]
Hi all, the unconference is only 3 weeks away now! On day 1 there will be a breakout blitz where all session organizers should advertise their sessions. 1 minute, 1 slide, let people know what you intend to do. Please prepare this slide in advance and add it right here (PDF please), by **September 20**.

**Comment by pancetta** [comment]
*ping*

**Comment by pancetta** [comment]
*PING* @dokempf @knarrff

**Comment by dokempf** [comment]
@pancetta Will do this in the morning.

**Comment by dokempf** [comment]
Here it is @pancetta  [breakout_blitz.pdf](https://github.com/DE-RSE/un-deRSE23-breakouts/files/12698145/breakout_blitz.pdf)

**Comment by pancetta** [comment]
Here is the main hub for taking notes: https://pad.gwdg.de/FkFJTslFQhq-UF3Es6q4rw#

**Comment by pancetta** [comment]
Have fun with the session(s)! Please add the pad you're using also here for people to see what you did. 

If possible, please prepare a 1 minute wrap up of your session for the farewell session on Thursday afternoon! What did you do in the session, how would you like to continue, how can people contribute after the unconference etc. We'll go through the blitz slides again one by one as in the blitz session.
