### ISSUE TITLE
Decentralising infrastructure

### ISSUE THREAD

**Issue by chillenzer** [DE-RSE/un-deRSE23-breakouts#5]
Hi everybody,

on RSEcon22, I found [this talk](https://inv.vern.cc/watch?v=1YqkBNbRr9s) very inspiring and think that this redecentralisation effort is very valuable, particularly (but not exclusively) for research. My experience is that German institutions are doing a lot better than many others in not too much relying on centralised commercial provider but that is based on a very small sample size and I'm sure there is still room for improvement.

Admittedly, I have very little knowledge about this from the technical side (not being in system administration myself so much) but I wanted to plant a seed here, so maybe more knowledgeable people can make a great breakout session that I will happily attend. =) I was thinking about discussions on where the optimum in the centralised/decentralised continuum for a prospering research environment might be, maybe interspersed with some success (or failure) stories and discussions/advice on what are the hurdles and pitfalls of implementing and using decentralised infrastructures. The latter is likely to imply both technical and bureaucratic/political ones.

Hope there's somebody out there to pick this up!

Best

**Comment by chillenzer** [comment]
I guess the most interesting thing for me would be to learn about the tech part of that. What solutions exist and how to hack them together in my little home server just for fun.

But the most impactful knowledge to get into the RSE community would probably be how to convince policy makers and university officials that they can benefit in the long run. Or if this not very subtly biased assumption about the outcome of such a discussion does not hold: What is needed for it to be beneficial. I've been involved in quite a few discussions where I tried to argue in favor of setting up such solutions and got turned down mostly along the line of "but you have to have someone to maintain that".

So, I guess any means of spreading this knowledge would be beneficial: A blog post with our results (potentially including an itemized list of pro/con arguments or a checklist of what you need to do) would be the very least. One could think bigger and maybe even sketch a training course for RSE(-ish) and sysadmin people on how to set that up. Realistic guides on the necessary resources are probably an important point conveyed in some form or another.

**Comment by pancetta** [comment]
Hi @chillenzer, thanks for your proposal! As we're (slowly) moving toward more specific submissions, could you please add more details to the proposal? I guess not everyone understands what this is about and how the session could look like. Do you already have collaborators or contributors in mind? If so, just ping them (e.g. right here) and ask for their input.

**Comment by chillenzer** [comment]
Hi, unfortunately not. Hoped for the idea to take wings by itself (or rather by other people's expertise). I could only ping @manning-ncsa. Maybe he's flattered enough to take over? I'm also aware that the state of Thuringia does a rather good job with this. I've prodded someone else from there, so we might get a response there. Otherwise, I'm afraid we have to come back to this idea in another year.

**Comment by manning-ncsa** [comment]
It is encouraging to see my presentation reaching people so far away @chillenzer. I cannot commit to anything concrete for this conference without being an attendee, though. That being said, perhaps this would be a good opportunity for me to take a trip to Deutschland this year!

**Comment by pancetta** [comment]
Hi again, any update here?

**Comment by chillenzer** [comment]
Nope, unfortunately not. I will try to stir others (like #7, #8, #13, #16) in the direction of including some of this but I don't have much to show for at the moment here.
