### ISSUE TITLE
telemetry for research software - automating provenance information creation in workflows

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/un-deRSE23-breakouts#7]
Closing the feedback loop for RSEs on software feature level can be important for bigger and more mature projects. Which parts of  software need more attention, etc.

Let's review what we can learn from software engineering in general and discuss if that applies to research software. Can there be GDPR compliant telemetry?

Additionally we can inspect that topic from the RDM (research data management) side. Can the "self awareness" of software be used, to generate provenance records to improve FAIRness of datasets and other software, e.g. a workflow adds itself as user to its dependencies to inform them. How is that coupled to software directories?

**Comment by pancetta** [comment]
Hi @StephanJanosch, thanks for the proposal! Do you have collaborators in mind for this, people you would like to see attending/contributing? If so, drag them in! As we're (slowly) moving toward more specific submissions, could you please add more details to the proposal? We'd need 1-3 people responsible for the BOS, a short abstract/appetizer incl. stuff attendees can take away from that and so on.

**Comment by StephanJanosch** [comment]
I don't know if @led02 and @sdruskat have any thoughts, as telemetry could be regarded as automated citation. Maybe this is also too far off. (telemetry endpoint in citation.cff to make transparent software is telemetry enabled. Giving the interested user a reference to look into telemetry analog to the GitHub repo activity graph). Not sure, if that makes sense

**Comment by pancetta** [comment]
Hi again! Any update here?

**Comment by HeidiSeibold** [comment]
I added a [label](https://github.com/DE-RSE/un-deRSE23-breakouts/labels) to this break-out. Can you check if you feel it is appropriate and change it if not? Let me know if you have any questions.

**Comment by HeidiSeibold** [comment]
Could you please answer the following questions for me?

### Who could be interested in collaborating on this?
(feel free to tag them with their GitHub username if they have one)

### How much time do you need for this?
(90 minutes or multiples thereof)

### Abstract
(Can be short)

**Comment by HeidiSeibold** [comment]
Hi @StephanJanosch  can you please respond by Tuesday morning, thanks 😃

**Comment by HeidiSeibold** [comment]
Hi @StephanJanosch do you still want to do this? If I do not hear anything, I cannot plan the sessions.

**Comment by pancetta** [comment]
@StephanJanosch Is this session actually going to happen?

**Comment by StephanJanosch** [comment]
Sorry missed your triggers. Nobody expressed interest. Not going to happen.

I got bombed with Github mails and did not saw the difference between orga issues and participant related issues. So ignored all of them. 😇
