### ISSUE TITLE
An Update on XML Technology

### ISSUE THREAD

**Issue by dmj** [DE-RSE/un-deRSE23-breakouts#9]
XML and its surrounding technologies have been around for almost two decades of continous improvement. Yet some conceptions of XML are rooted in experiences or stories from the hight of the XML hype cycle in the early 2000s.

I would like to spend initial 90 minutes to discuss the usage of XML and XML technologies in research software engineering. I can offer a 15 minute quick update on the current XML ecosystem to initiate a discussion.

Some of the technologies I have in mind:

- Transformation: XSLT 3.0
- Automation: XProc
- Validation: ISO Schematron, RELAXNG, W3C XML Schema, DTD
- Auxilliary: XML Catalogs

**Comment by pancetta** [comment]
Hi @dmj, thanks a lot for your proposal! Do you already have collaborators/contributors in mind? If so, ping them (e.g. right here), so that they are aware of your proposal. We'd need 1-3 people responsible for each BOS, a short appetizer incl. possible outcomes, and some details on how you would like to organize the session.

**Comment by pancetta** [comment]
Hi again, any news here?

**Comment by HeidiSeibold** [comment]
Hi @dmj, are you still interested in pursuing this break-out idea?

**Comment by HeidiSeibold** [comment]
I added a [label](https://github.com/DE-RSE/un-deRSE23-breakouts/labels) to this break-out. Can you check if you feel it is appropriate and change it if not? Let me know if you have any questions.

**Comment by dmj** [comment]
Hi Heidi! Given that there hasn't been much interest in this suggested breakout I would suggest to close it.

**Comment by HeidiSeibold** [comment]
Thanks @dmj for the feedback. Hope you'll join us still 😃 

Feel free to check out and comment on the other suggestions!
